
import sqlite3
import json

DB_PATH = "/Users/phillipwalters/Projects/askeo/repo/backend/exercise_v2.db"

# ---------------------------------------------------------------------------
# Granular movement pattern taxonomy — CHECK ISOLATION BEFORE COMPOUND
# ---------------------------------------------------------------------------

MOVEMENT_PATTERNS = {
    # ===== ISOLATION PATTERNS (checked first to avoid conflicts) =====
    
    # Push isolation
    "push_flat_isolation": [
        "chest fly", "cable fly", "pec deck", "machine fly",
        "dumbbell fly", "incline fly", "decline fly",
        "cable crossover", "low cable fly", "high cable fly",
        "mid cable fly", "upper chest crossover", "chest crossovers",
        "cable fly on exercise ball", "dumbbell fly on exercise ball",
        "pullover", "barbell pullover", "dumbbell pullover",
        "around pullover", "pullover on exercise ball",
        "supine triceps extension",  # lying supine triceps extension
        "cable lying fly", "cable low fly", "cable middle fly",
        "cable standing fly", "cable standing up straight crossovers",
        "cable cross-over variation", "cable upper chest crossovers",
        "one arm fly on exercise ball",  # catches dumbbell and cable
        "dumbbell one arm bench fly", "dumbbell decline one arm fly",
        "dumbbell one arm fly on exercise ball", "cable one arm fly on exercise ball",
        "dumbbell lying one arm press",  # lying one arm press = chest isolation
        "dumbbell one arm fly", "dumbbell one arm fly on exercise ball",
        "dumbbell one leg fly on exercise ball",
        "dumbbell iron cross",
        "lever seated fly",
        "dumbbell lying elbow press",
        "dumbbell incline one arm fly",
    ],
    "push_vertical_isolation": [
        "lateral raise", "side raise", "side lateral", "dumbbell lateral",
        "cable lateral", "machine lateral", "lever lateral",
        "upright row", "barbell upright row", "dumbbell upright row",
        "cable upright row", "smith upright row",
        "front raise", "dumbbell front raise", "cable front raise",
        "rear delt raise", "rear lateral raise", "lying rear delt",
        "seated rear lateral", "cable rear delt", "dumbbell rear delt",
        "reverse fly", "rear fly", "bent over rear delt",
        "y-raise", "t-raise", "w-raise", "i-raise",
        "full can lateral", "scott press",
        "shoulder raise", "incline raise", "incline shoulder raise",
        "incline rear lateral",
        "dumbbell raise", "dumbbell standing alternate raise",
        "dumbbell standing raise", "standing dumbbell raise",
    ],
    "wrist_curl": [
        "wrist curl", "wrist curls",
        "palms down wrist curl", "palms up wrist curl",
        "barbell wrist curl", "barbell palms down wrist curl",
        "barbell palms up wrist curl",
        "dumbbell wrist curl", "dumbbell over bench wrist curl",
        "dumbbell over bench neutral wrist curl",
        "dumbbell over bench one arm wrist curl",
        "dumbbell over bench one arm neutral wrist curl",
        "dumbbell over bench one arm reverse wrist curl",
        "dumbbell over bench reverse wrist curl",
        "cable wrist curl", "cable standing back wrist curl",
        "cable reverse wrist curl",
        "smith seated wrist curl", "smith standing back wrist curl",
        "reverse wrist curl", "wrist curl reverse",
        "barbell reverse wrist curl", "barbell reverse wrist curl v. 2",
        "dumbbell reverse wrist curl",
        "over bench reverse wrist curl", "over bench one arm reverse wrist curl",
        "one arm reverse wrist curl",
        "seated wrist curl", "seated neutral wrist curl",
        "seated palms up wrist curl",
        "neutral wrist curl",
        "finger curls", "dumbbell finger curls",
        "one arm wrist curl",
        "band wrist curl", "band reverse wrist curl",
        "gripper", "hand gripper", "lever gripper",
    ],

    "push_tricep_isolation": [
        "tricep pushdown", "tricep extension", "skull crusher",
        "triceps extension", "overhead tricep", "seated tricep",
        "lying tricep", "cable tricep", "dumbbell tricep",
        "ez bar tricep", "rope pushdown", "v-bar pushdown",
        "barbell tricep", "tate press", "lying extension",
        "cable overhead tricep", "standing tricep extension",
        "seated tricep extension", "incline tricep extension",
        "tricep kickback", "french press", "barbell french",
        "decline skull", "decline tricep",
        "cable kickback", "dumbbell kickback", "kickback",
        "one arm tricep", "single arm tricep",
        "triceps press",  # triceps press (generic)
        "cable pushdown", "cable pushdown (with rope", "cable pushdown (straight arm",
        "cable rope pushdown", "cable v-bar pushdown",
        "incline tricep extension", "cable incline pushdown",
        "incline pushdown", "reverse-grip pushdown", "reverse grip tricep",
        "cable reverse-grip pushdown", "cable reverse-grip triceps pushdown",
        "cable drag curl",
        "cable concentration extension (on knee)",
        "cable forward raise",
        "cable standing lift",
        "cable palm rotational row",
        "dumbbell lying alternate extension",
        "dumbbell lying elbow extension",
        "dumbbell lying single extension",
        "dumbbell lying supine curl",
        "dumbbell lying wide curl",
        "dumbbell seated bench extension",
        "dumbbell standing one arm extension",
        "dumbbell one arm seated neutral wrist curl",
        "dumbbell seated neutral wrist curl",
        "dumbbell seated palms up wrist curl",
        "dumbbell one arm wrist curl",
        "dumbbell reverse wrist curl",
        "dumbbell over bench wrist curl",
        "dumbbell over bench neutral wrist curl",
        "dumbbell over bench one arm wrist curl",
        "dumbbell over bench one arm neutral wrist curl",
        "dumbbell over bench one arm reverse wrist curl",
        "dumbbell over bench reverse wrist curl",
        "barbell wrist curl", "barbell wrist curl v. 2",
        "barbell reverse wrist curl", "barbell reverse wrist curl v. 2",
        "barbell standing back wrist curl",
        "cable wrist curl", "cable standing back wrist curl",
        "cable reverse wrist curl",
        "ez barbell close-grip curl",
        "ez barbell anti gravity press",
        "finger curls", "dumbbell finger curls",
    ],
    "pull_bicep_isolation": [
        "bicep curl", "biceps curl", "barbell curl", "dumbbell curl",
        "cable curl", "hammer curl", "preacher curl", "prone curl",
        "incline curl", "concentration curl", "zottman curl",
        "spider curl", "standing curl", "seated curl",
        "lying curl", "alt curl", "alternate curl",
        "cross body curl", "inner bicep",
        "ez-bar curl", "ez bar curl", "olympic curl",
        "curl machine", "lever bicep", "machine bicep",
        "assisted curl", "seated one arm curl", "cable one arm curl",
        "one arm curl", "reverse grip curl",
        "cable overhead curl", "cable overhead curl on exercise ball",
        "cable seated curl", "cable seated overhead curl",
        "cable two arm curl on incline bench",
        "cable standing inner curl", "cable standing curl",
        "cable lying curl", "cable lying close-grip curl",
        "cable one arm curl", "dumbbell one arm curl",
        "high curl", "dumbbell high curl",
        "barbell standing close grip curl", "barbell standing wide-grip curl",
        "dumbbell seated alternate curl",
        "dumbbell lying supine curl",
        "dumbbell lying wide curl",
        "dumbbell pronation curl",
        "dumbbell supination curl",
        "cable close grip curl",
        "cable drag curl",
        "barbell drag curl",
        "barbell side bent v. 2",
        "barbell standing twist",
        "bent knee lying twist (male)",
        "reverse hyper extension (on stability ball)",
        "gorilla chin",
        "side-to-side chin",
        "spell caster",
        "stalder press",
    ],
    "reverse_curl": [
        "reverse curl", "reverse grip curl", "reverse grip",
        "barbell reverse curl", "dumbbell reverse curl",
        "cable reverse curl", "ez bar reverse curl",
        "standing reverse curl", "seated reverse curl",
    ],
    "reverse_wrist_curl": [
        "reverse wrist curl", "wrist curl reverse",
        "barbell reverse wrist curl", "dumbbell reverse wrist curl",
        "cable reverse wrist curl",
        "over bench reverse wrist curl", "over bench one arm reverse wrist curl",
        "one arm reverse wrist curl",
    ],
    "wrist_curl": [
        "wrist curl", "wrist curls",
        "palms down wrist curl", "palms up wrist curl",
        "barbell wrist curl", "barbell palms down wrist curl",
        "barbell palms up wrist curl",
        "dumbbell wrist curl", "dumbbell over bench wrist curl",
        "dumbbell over bench neutral wrist curl",
        "dumbbell over bench one arm wrist curl",
        "dumbbell over bench one arm neutral wrist curl",
        "dumbbell over bench one arm reverse wrist curl",
        "cable wrist curl", "cable standing back wrist curl",
        "seated wrist curl", "seated neutral wrist curl",
        "seated palms up wrist curl",
        "finger curls", "dumbbell finger curls",
        "neutral wrist curl",
        "one arm wrist curl",
        "gripper", "hand gripper", "lever gripper",
    ],
    "pull_vertical_isolation": [
        "straight arm pulldown", "straight arm pull",
    ],
    "pull_horizontal_isolation": [
        "rear delt fly", "rear delt raise", "reverse fly",
        "bent over rear delt", "lying rear delt", "seated rear lateral",
        "face pull", "face pulldown", "cable face pull",
        "rear lateral raise", "side lateral raise",
        "one arm lateral bent-over", "cable rear delt row",
    ],
    "squat_isolation": [
        "leg extension", "machine leg extension", "knee extension",
        "sled leg extension",
    ],
    "hinge_isolation": [
        "leg curl", "lying leg curl", "seated leg curl", "standing leg curl",
        "machine leg curl", "lever leg curl", "cable leg curl",
        "hamstring curl", "inverse leg curl",
        "glute ham", "glute-ham",
        "cable hip adduction", "hip adduction", "lever hip adduction",
        "hyperextension", "reverse hyperextension",
    ],
    "tricep_isolation": [
        # Additional tricep patterns (same as push_tricep_isolation for completeness)
        "tricep pushdown", "tricep extension", "skull crusher",
        "triceps extension", "overhead tricep", "seated tricep",
        "lying tricep", "cable tricep", "dumbbell tricep",
        "ez bar tricep", "rope pushdown", "v-bar pushdown",
        "barbell tricep", "tate press", "lying extension",
        "cable overhead tricep", "standing tricep extension",
        "seated tricep extension", "incline tricep extension",
        "tricep kickback", "french press", "barbell french",
        "decline skull", "decline tricep",
        "cable kickback", "dumbbell kickback", "kickback",
        "one arm tricep", "single arm tricep",
        " reverse-grip tricep", "reverse grip tricep",
        "cable reverse-grip pushdown", "cable reverse-grip tricep",
        "triceps press",
    ],
    "calf_raise": [
        "calf raise", "calf raises", "standing calf", "seated calf",
        "leg press calf", "machine calf", "smith calf",
        "donkey calf", "one leg calf", "single leg calf",
        "toe raise", "lever calf", "sled calf",
        "rotary calf", "calf press",
    ],

    # ===== MOBILITY / HELPER PATTERNS (checked before compound) =====
    
    "mobility_hip": [
        "hip flexor stretch", "pigeon", "90/90", "90 90",
        "world greatest stretch", "hip mobility", "frog stretch",
        "butterfly stretch", "butterfly", "groin stretch",
        "figure four stretch", "figure 4", "hip opener",
        "shin box", "hip circle", "hip rotate",
        "dynamic hip", "hip stretch", "stretch hip",
        "seated glute stretch", "glute stretch", "piriformis stretch",
        "intermediate hip flexor", "quad stretch",
        "side lying hip adduction", "side lying hip",
        "straight leg outer hip",
        "chair leg extended stretch",
        "lying (side) quads stretch",
        "roller back stretch",
        "roller seated shoulder flexor depresor retractor",
        "roller seated single leg shoulder flexor depresor retractor",
        "standing lateral stretch",
        "triceps stretch",
        "upward facing dog",
        "glutes stretch",
        "hip raise (bent knee)",
        "cable hip adduction",
        "band lying hip internal rotation",
        "band hip flexor",
        "kettlebell figure 8",
        "monster walk", "lateral walk", "band walk", "shuffle walk",
        "barbell lying lifting", "lying lifting on hip",
        "resistance band shuttle", "band shuttle", "shuttle",
        "hip external rotation", "hip internal rotation",
        "band hip external rotation", "band hip internal rotation",
        "lying hip external rotation", "seated hip external rotation",
    ],
    "mobility_shoulder": [
        "shoulder dislocate", "shoulder dislocation", "band shoulder mobility",
        "cable shoulder stretch", "doorway chest stretch", "doorway stretch",
        "shoulder stretch", "upper back stretch", "lat stretch",
        "band shoulder mobility", "shoulder mobility",
        "arm slinger", "swing 360", "chest stretch",
        "back pec stretch", "behind head chest stretch",
        "rear deltoid stretch", "rear delt stretch",
        "side neck stretch", "neck side stretch", "front and back neck stretch",
        "standing archer",
    ],
    "mobility_spine": [
        "cat cow", "cat-cow", "child's pose", "child pose",
        "cobra", "upward dog", "downward dog", "downward-facing dog",
        "spine twist", "spine stretch", "thoracic twist",
        "thread the needle", "open book", "book opener",
        "prayer stretch", "standing spinal", "standing spine",
        "seated spinal", "seated spine",
        "lower back stretch", "lower back curl",
        "sphinx", "toe touch sit", "toe touch",
        "forward bend", "standing forward",
        "march sit (wall)",
        "posterior step to overhead reach",
        "pull-in (on stability ball)",
        "rear leg lift",
        "dumbbell lying pronation", "dumbbell lying pronation on floor",
        "dumbbell lying supination", "dumbbell lying supination on floor",
        "dumbbell lying elbow press",
        "dumbbell lying femoral",
        "dumbbell lying hammer press",
        "dumbbell lying one arm deltoid rear",
        "windmill", "kettlebell windmill", "kettlebell advanced windmill",
        "kettlebell double windmill",
    ],
    "mobility_ankle": [
        "ankle mobility", "ankle circle", "ankle stretch",
        "calf stretch", "runner's stretch", "runners stretch",
        "ankle rock", "knee to wall", "knee over toe",
        "single leg balance", "ankle dorsal flexion",
        "peroneals stretch", "posterior tibialis stretch",
        "plantar flexion", "foot plantar", "foot eversion", "foot inversion",
        "calf push stretch", "cable calf stretch",
        "seated calf stretch", "soleus stretch", "gastroc stretch",
        "balance board", "balance pad",
        "foot external rotation", "foot internal rotation",
    ],
    "mobility_wrist": [
        "wrist circle", "wrist mobility", "wrist stretch",
        "wrist rollerer", "wrist flexion", "wrist extension",
        "side wrist pull stretch", "wrist pull stretch",
    ],
    "core_anti_extension": [
        "plank", "front plank", "side plank", "plank hold",
        "dead bug", "deadbug", "ab wheel", "wheel rollout",
        "wheel rollerout", "hollow body", "hollow hold",
        "stir the pot", "plank saw", "plank tap",
        "body saw", "roller body saw", "stability ball rollout",
        "suspension plank", "trx plank",
        "suspended abdominal fallout", "suspended row",
        "roll outs into v sits", "roll over",
        "incline leg hip raise", "incline leg raise",
        "barbell rollerout", "barbell rollerout from bench",
        "standing ab rollerout", "barbell standing ab rollerout",
    ],
    "core_anti_rotation": [
        "pallof press", "cable pallof", "band pallof",
        "russian twist", "cable russian", "medicine ball twist",
        "landmine rotation", "landmine 180", "cable wood chop",
        "wood chop", "cable chop", "band chop",
        "hay baler", "cable rotational", "band rotational",
        "seated twist", "cable seated twist", "barbell seated twist",
        "twist hip lift", "weighted seated twist",
        "prone twist on stability ball",
        "cable judo flip",
        "cable twist", "cable twist (up-down)", "cable twisting pull",
        "lever kneeling twist",
    ],
    "core_flexion": [
        "crunch", "sit-up", "sit up", "cable crunch",
        "decline crunch", "decline sit-up", "ball crunch",
        "exercise ball crunch", "machine crunch", "lever crunch",
        "weighted crunch", "oblique crunch", "side bend",
        "dumbbell side bend", "cable side bend", "barbell side bend",
        "cross body crunch", "elbow to knee", "elbow-to-knee",
        "superman", "superman legs", "pirate", "supper legs",
        "back extension", "prone back extension",
        "curl-up", "janda sit-up", "abdominal curl",
        "alternate heel touchers", "heel touchers",
        "v-sit", "v sit", "v-sit on floor", "jackknife sit-up",
        "butt-ups", "cocoons",
        "barbell side bent v. 2",
        "barbell standing twist",
        "bent knee lying twist (male)",
        "barbell leg twist press",
        "weighted lying side lifting head (with head harness)",
        "weighted lying neck extension (with head harness)",
        "weighted lying neck flexion (with head harness)",
        "weighted standing neck extension (with head harness)",
        "weighted seated neck extension (with head harness)",
        "cable seated neck extension (with head harness)",
        "cable seated neck flexion (with head harness)",
        "lever neck extension (plate loaded)",
        "lever neck left side flexion (plate loaded)",
        "lever neck right side flexion (plate loaded)",
        "isometric wipers",
        "swimmer kicks v. 2 (male)",
    ],
    "core_circumduction": [
        "hanging leg raise", "hanging knee raise", "hanging hip raise",
        "hanging straight leg", "captains chair leg raise",
        "captain's chair", "vertical leg raise", "leg raise",
        "lying leg raise", "lying hip raise", "flutter kick",
        "scissor kick", "bicycle crunch", "air bike",
        "dragon flag", "flag", "l-sit",
        "hanging pike", "weighted hanging leg-hip raise",
        "hanging oblique knee raise", "hanging straight twisting leg hip raise",
        "roll overs into v sits",
        "leg pull in flat bench", "leg-hip raise",
        "pelvic tilt", "standing pelvic tilt",
        "lower back curl",
    ],
    "core_carries": [
        "farmer walk", "farmer's walk", "suitcase carry", "suitcase walk",
        "overhead carry", "farmers walk", "grip carry",
        "trap bar carry", "rack carry", "front rack carry",
        "single arm carry", "one arm carry",
        "bottoms-up", "bottoms up",
    ],
    "shoulder_external_rotation": [
        "shoulder external rotation", "shoulder rotation",
        "cable rotation", "dumbbell external rotation",
        "lying external rotation", "standing external rotation",
        "band pull-apart", "pull apart",
        "cable pull-apart",
        "thoracic extension", "thoracic rotation",
        "seated shoulder internal rotation", "shoulder internal rotation",
        "cable seated shoulder internal rotation",
        "seated hip internal rotation",
        "dumbbell lying pronation",
        "dumbbell lying pronation on floor",
        "dumbbell lying supination",
        "dumbbell lying supination on floor",
        "dumbbell one arm rotate",
        "dumbbell seated one arm rotate",
        "dumbbell standing around world",
        "dumbbell w-press",
        "weighted round arm",
        "spell caster",
        "side-to-side chin",
        "side lying one hand raise",
        "dumbbell lying elbow press",
        "band face pull", "face pull",
    ],
    "scapular_retraction": [
        "scapular pull-up", "scapular push-up", "scapula dip",
        "prone y-raise", "prone t-raise", "prone i-raise",
        "prone raise", "lying y-raise", "lying t-raise",
        "rear delt row", "rear delt raise", "bent over rear delt",
        "band scapular", "cable scapular",
        "chin tuck", "assisted chin tuck",
    ],

    # ===== COMPOUND PATTERNS =====
    
    "push_up": [
        "push-up", "pushup", "push up",
        "close-grip push-up", "incline push-up", "decline push-up",
        "kneeling push-up", "diamond push-up", "clock push-up",
        "push-up to side plank", "chest tap push-up",
        "incline close-grip push-up",
        "full planche push-up", "planche push-up",
        "handstand push-up", "handstand",
        "muscle up", "muscle-up", "kipping muscle up",
        "weighted muscle up",
        "planche", "front lever", "back lever", "frog planche",
        "full planche", "full maltese", "straddle planche", "straddle maltese",
        "lean planche", "tuck planche",
        "band alternating v-up", "band v-up",
        "push and pull bodyweight",
        "shoulder tap",
        "hug knees to chest",
        "kick out sit",
        "otis up",
        "exercise ball alternating arm ups",
        "exercise ball hug",
        "exercise ball one leg prone lower body rotation",
    ],
    "push_flat_compound": [
        "bench press", "flat bench", "chest press", "machine chest press",
        "smith bench press", "floor press", "pin press", "landmine press",
        "neutral grip bench", "reverse grip bench", "pause bench",
        "dumbbell bench press", "dumbbell flat press",
        "dumbbell press", "dumbbell flat",
        "barbell bench", "barbell chest press",
        "cable chest press", "cable press on exercise ball",
        "seated chest press", "lever chest press",
        "incline press on exercise ball",  # handled by incline below
        "machine inner chest press", "inner chest press",
        "floor fly (with barbell)",  # floor fly with barbell is actually a compound press variation
        "elevator",  # elevator press
        "body-up",  # body-up is a compound push
        "isometric chest squeeze",  # chest squeeze
        "sledge hammer",  # sledge hammer is a full body pull but mostly a grip/upper back exercise
        "smith decline reverse-grip press",
        "smith incline reverse-grip press",
        "smith reverse-grip press",
        "barbell incline reverse-grip press",
        "barbell palms down wrist curl over a bench",
        "barbell palms up wrist curl over a bench",
        "dumbbell standing palms in press",
        "medicine ball chest pass", "medicine ball chest push",
        "medicine ball chest push from 3 point stance",
        "medicine ball chest push multiple response",
        "medicine ball chest push single response",
        "medicine ball supine chest throw",
        "medicine ball overhead throw",
        "one arm slam (with medicine ball)",
        "kettlebell bent press", "kettlebell seesaw press",
        "kettlebell extended range one arm press on floor",
    ],
    "push_incline_compound": [
        "incline bench press", "incline press", "incline dumbbell press",
        "incline chest press", "smith incline bench",
        "incline dumbbell", "dumbbell incline press",
        "dumbbell incline bench", "dumbbell incline palm-in press",
        "dumbbell incline one arm press", "dumbbell incline alternate press",
        "dumbbell incline hammer press", "incline hammer press",
        "seated incline press", "lever incline chest press",
        "cable incline bench press", "cable incline press",
        "incline press on exercise ball", "dumbbell press on exercise ball",
        "dumbbell incline one arm press on exercise ball",
        "dumbbell incline two arm extension",  # this is actually a tricep extension, but incline
        "dumbbell seated alternate press", "seated alternate press",
        "dumbbell seated bench press", "dumbbell bench seated press",
        "dumbbell neutral grip bench press",
        "dumbbell palms in incline bench press",
        "dumbbell pronate-grip",  # pronate-grip triceps but on incline can be push
        "dumbbell incline one arm hammer press",
        "dumbbell incline one arm hammer press on exercise ball",
        "dumbbell one arm hammer press on exercise ball",
        "dumbbell incline breeding",
    ],
    "push_decline_compound": [
        "decline bench press", "decline press", "decline dumbbell press",
        "decline dumbbell", "dumbbell decline press",
        "dumbbell decline bench", "dumbbell decline one arm press",
        "dumbbell decline hammer press", "decline hammer press",
        "smith decline press", "smith decline bench",
        "decline seated press", "lever decline chest press",
        "cable decline press", "cable decline bench press",
        "barbell decline wide-grip press",
        "dumbbell decline one arm hammer press",
        "dumbbell decline twist fly",
        "dumbbell incline twisted flyes",
        "cable decline one arm press",
    ],
    "push_vertical_compound": [
        "overhead press", "military press", "shoulder press", "arnold press",
        "push press", "push jerk", "clean and press", "seated shoulder press",
        "standing shoulder press", "behind neck press", "z press",
        "bradford press", "bradford rocky press", "seated bradford",
        "standing bradford press", "barbell seated bradford rocky press",
        "cuban press", "dumbbell cuban press",
        "thruster", "barbell thruster", "kettlebell thruster",
        "dumbbell push press", "dumbbell thruster",
        "dumbbell seated shoulder press", "seated press",
        "dumbbell seated alternate shoulder", "seated alternate shoulder",
        "dumbbell standing alternate overhead press",
        "dumbbell standing overhead press", "standing overhead press",
        "dumbbell alternating press", "kettlebell alternating press",
        "kettlebell alternating press on floor",
        "dumbbell arnold press", "arnold press v. 2",
        "kettlebell arnold press",
        "dumbbell push press", "push press dumbbell",
        "landmine 180",
        "dumbbell one arm press", "dumbbell one arm press on exercise ball",
        "cable one arm press", "cable one arm press on exercise ball",
        "cable overhead press", "cable shoulder press",
        "cable alternate shoulder press",
        "dumbbell press on exercise ball", "incline press on exercise ball",
        "dumbbell alternate side press",
        "smith incline shoulder raises", "smith shoulder press",
        "dumbbell standing one arm palm in press",
        "dumbbell palms in press",
        "smith decline reverse-grip press",
        "smith incline reverse-grip press",
        "smith reverse-grip press",
        "barbell incline reverse-grip press",
        "barbell palms down wrist curl over a bench",
        "barbell palms up wrist curl over a bench",
        "dumbbell standing palms in press",
        "medicine ball chest pass", "medicine ball chest push",
        "medicine ball chest push from 3 point stance",
        "medicine ball chest push multiple response",
        "medicine ball chest push single response",
        "medicine ball supine chest throw",
        "medicine ball overhead throw",
        "one arm slam (with medicine ball)",
        "kettlebell bent press", "kettlebell seesaw press",
        "kettlebell extended range one arm press on floor",
    ],
    "push_tricep_compound": [
        "dip", "chest dip", "bench dip", "tricep dip",
        "close-grip bench", "close grip bench", "jm bench",
        "close-grip push-up",
        "ez-bar close-grip bench press",
        "close-grip press", "dumbbell close grip press",
        "dumbbell close-grip press", "dumbbell lying close-grip press",
        "barbell lying close-grip press", "barbell close-grip press",
        "ez barbell decline close grip face press",
        "barbell decline close grip to skull press",
        "barbell seated close grip behind neck triceps extension",
        "ez barbell jm bench press", "barbell jm bench press",
        "barbell pin presses",
        "dumbbell tate press",
        "triceps press",  # triceps press can be compound depending on type
    ],
    "pull_vertical_compound": [
        "pull-up", "chin-up", "pull up", "chin up",
        "lat pulldown", "cable pulldown", "pulldown",
        "twin handle lat", "pro lat bar",
        "cable lat pulldown full range of motion",
        "assisted pull-up", "assisted chin-up", "assisted standing pull-up",
        "assisted standing chin-up", "lever assisted chin-up",
        "gironda sternum chin", "sternum chin",
        "rocky pull-up pulldown",
        "shoulder grip pull-up", "mixed grip chin-up",
        "close grip chin-up", "narrow grip pull-up",
        "wide grip pull-up", "wide grip rear pull-up",
        "rear pull-up", "rear chin-up",
        "bench pull-ups", "pull up (neutral grip)",
        "chin-ups (narrow parallel grip)",
        "l-pull-up", "front lever",  # front lever is a pull hold
        "back lever",  # back lever is a pull hold
        "skin the cat",  # skin the cat is a pull mobility/hold
        "elevator",  # already listed above
    ],
    "pull_horizontal_compound": [
        "bent over row", "barbell row", "dumbbell row",
        "seated row", "cable row", "lever row", "t-bar row",
        "pendlay row", "chest supported row", "incline row",
        "machine row", "smith row", "hammer row",
        "kroc row", "yates row", "one arm row",
        "cable seated row", "cable row",
        "seated chest row", "cable seated wide-grip row",
        "cable decline seated wide-grip row",
        "cable floor seated wide-grip row",
        "cable low seated row", "cable straight back seated row",
        "cable high row", "cable seated high row",
        "cable kneeling row", "cable high row kneeling",
        "cable thibaudeau kayak row", "kayak row",
        "cable reverse-grip straight back seated high row",
        "cable one arm row", "one arm cable row",
        "dumbbell bent over row", "dumbbell one arm row",
        "dumbbell incline row", "incline dumbbell row",
        "cable standing row (v-bar)", "cable standing twist row (v-bar)",
        "cable upper row",
        "band one arm standing low row",
        "bodyweight standing close-grip row",
        "resistance band seated straight back row",
        "one arm towel row",
        "smith standing back wrist curl",
        "smith seated wrist curl",

        "barbell bent over row", "barbell pendlay row",
        "barbell incline row", "barbell t-bar row",
        "lever bent over row", "lever bent-over row",
        "lever high row", "lever seated row",
        "lever t bar row", "lever unilateral row",
        "lever alternating narrow grip seated row",
        "lever narrow grip seated row",
        "inverted row", "inverted row bent knees", "inverted row on bench",
        "inverted row v. 2", "inverted row with straps",
        "bodyweight standing row", "bodyweight squatting row",
        "suspended row", "smith narrow row",
        "cambered bar lying row",
        "cable incline bench row",
        "cable one arm straight back high row",
        "cable rope extension incline bench row",
        "cable seated one arm alternate row",
        "dumbbell one arm bent-over row",
        "kettlebell renegade row", "kettlebell alternating renegade row",
        "kettlebell alternating row", "kettlebell two arm row",
        "lever one arm lateral high row",
    ],
    "pull_shrug": [
        "shrug", "trap shrug", "barbell shrug", "dumbbell shrug",
        "cable shrug", "smith shrug", "lever shrug", "machine shrug",
        "gripless shrug",
        "smith back shrug", "smith shrug",
        "dumbbell decline shrug", "dumbbell incline shrug",
        "lever gripless shrug",
    ],
    "squat_compound": [
        "back squat", "front squat", "full squat", "squat",
        "barbell squat", "goblet squat", "smith squat",
        "leg press", "machine squat", "belt squat",
        "zercher squat", "overhead squat", "pause squat",
        "stretch squat", "box squat", "safety bar squat",
        "squat variation", "sled 45 degree leg wide press",
        "sled 45° leg wide press", "sled leg wide press",
        "sled 45° calf press", "sled calf press",
        "sled lying calf press",
        "calf push stretch with hands against wall",
    ],
    "lunge_compound": [
        "lunge", "forward lunge", "reverse lunge", "walking lunge",
        "bulgarian split", "split squat", "step up", "step-up",
        "curtsy lunge", "lateral lunge", "side lunge",
        "dumbbell lunge", "barbell lunge", "kettlebell lunge",
        "smith lunge",
        "single leg platform slide", "platform slide",
    ],
    "squat_bodyweight": [
        "bodyweight squat", "air squat", "wall sit", "wall sit hold",
        "isometric squat", "half squat", "quarter squat",
        "half knee bends", "knee bends",
    ],
    "hinge_compound": [
        "deadlift", "romanian deadlift", "rdl", "stiff leg deadlift",
        "straight leg deadlift", "sumo deadlift", "trap bar deadlift",
        "kettlebell swing", "good morning", "glute-ham raise",
        "back extension", "hyperextension", "reverse hyperextension",
        "creates deadlift", "block pull", "rack pull",
        "deficit deadlift", "snatch grip deadlift",
        "barbell good morning", "dumbbell good morning",
        "glute ham raise", "glute ham",
        "clean", "power clean", "snatch", "clean and jerk",
        "hang clean", "kettlebell clean", "kettlebell hang clean",
        "one arm clean", "one arm snatch", "one arm jerk",
        "double clean", "double jerk", "double snatch",
        "alternating hang clean", "double alternating hang clean",
        "kettlebell bottoms up clean",
        "bottoms up clean",
        "snatch pull", "clean pull",
        "dumbbell clean", "dumbbell snatch",
        "barbell clean", "barbell snatch",
        "barbell weightlifting complex",
        "clean and jerk", "jerk",
        "olympic barbell",
        "single leg deadlift", "single leg rdl",
        "barbell skier", "skier",
        "sumo high pull", "kettlebell sumo high pull", "sumo pull",
        "band pull through", "pull through",
    ],
    "hip_compound": [
        "hip thrust", "glute bridge", "bridge", "barbell hip thrust",
        "single leg bridge", "frog pump", "glute kickback", "hip kickback",
        "hip abduction", "hip extension",
        "fire hydrant", "clamshell", "lateral walk",
        "banded hip thrust",
        "hip raise", "hip raise (bent knee)", "bent knee hip raise",
        "straight leg hip bridge", "straight leg bridge",
        "smith hip raise",
        "band hip lift", "twist hip lift",
        "hip adduction", "leg adduction",
        "side hip", "side hip (on parallel bars)",
        "hip lift",
        "cable pull through (with rope)",
        "cable rear drive",
        "dumbbell sumo pull through",
    ],

    # ===== SPECIAL CASES =====
    
    "cardio_plio": [
        "burpee", "jump squat", "jump lunge", "box jump",
        "scissor jumps", "star jump", "jack jump", "astride jumps",
        "jack burpee", "dumbbell burpee", "burpee",
        "jump rope", "double under jump rope",
        "skips", "skip", "quick feet", "quick feet run", "quick feet v. 2",
        "broad jump", "broad jump to vertical", "single leg board jump",
        "single leg vertical jump", "jump box over",
        "forward jump", "backward jump", "backward run", "backwards run",
        "back and forth step", "run", "run (equipment)",
        "wind sprint", "wind sprints", "sprints", "sprint",
        "walking on incline treadmill", "walking on stepmill",
        "walk elliptical cross trainer", "walk wave machine",
        "spin hook kick", "roundhouse kick", "heel push kick",
        "front snap kick", "side kick", "front leg hook kick",
        "rear leg hook kick", "front groin kick", "rear axe kick",
        "rear axe kick", "spin back kick",
        "high knee against wall", "mountain climber",
        "bear crawl", "bear crawl", "crab twist toe touch",
        "inchworm", "inchworm v. 2",
        " skater hops", "skater hops", "shuffle", "ski step", "ski erg",
        "ski ergometer", "cycle cross trainer", "stationary bike run",
        "stationary bike walk", "elliptical",
        "battling ropes", "battle rope", "rope climb",
        "hands bike", "upper body ergometer",
        "hands clasped circular toe touch", "arms apart circular toe touch",
        "circular toe touch", "side-to-side toe touch", "two toe touch",
        "toe touch", "one arm against wall",
        "prancing", "zigzag hops", "prancing",
        "prancing", "broad jump", "jump",
        "scissor jumps (male)", "star jump (male)", "jack jump (male)",
        "astride jumps (male)", "semi squat jump",
        "jump lunge", "jumping lunges",
        "backward jump", "forward jump",
        "box jump down with one leg stabilization",
        "single leg board jump",
        "single leg vertical jump",
        "broad jump to vertical",
        "jump box over (male)",
        "standing calves", "calf stretch",
        "ankle dorsal flexion",
        "resistance band foot plantar flexion",
        "resistance band foot eversion",
        "resistance band foot inversion",
        "sledge hammer",
        "tire flip", "car flip",
        "keg toss", "fingal's fingers",
        "strongman",
        " weighted round arm",
        "weighted svend press",
        "svend press",
        "weighted standing hand squeeze",
        "weighted hanging leg-hip raise",
        "weighted kneeling step with swing",
        "weighted muscle up",
        "roll overs into v sits",
        "ankle circles",
        "wrist circles", "wrist circles",
        "leg up hamstring stretch",
        "hamstring stretch",
        "calf push stretch",
        "circles knee stretch",
        "iron cross stretch",
        "rear deltoid stretch",
        "seated wide angle pose sequence",
        "seated piriformis stretch",
        "seated lower back stretch",
        "seated glute stretch",
        "side lying floor stretch",
        "side lying hip adduction (male)",
        "side lying adductor stretch",
        "side wrist pull stretch",
        "side push neck stretch",
        "side neck stretch",
        "neck side stretch",
        "front and back neck stretch",
        "assisted side lying adductor stretch",
        "assisted prone hamstring",
        "assisted prone lying quads stretch",
        "assisted prone rectus femoris stretch",
        "assisted lying calves stretch",
        "assisted lying glutes stretch",
        "assisted lying gluteus and piriformis stretch",
        "assisted seated pectoralis major stretch",
        "behind head chest stretch",
        "back pec stretch",
        "dynamic chest stretch",
        "chest stretch with exercise ball",
        "upper back stretch",
        "lat stretch", "exercise ball lat stretch",
        "exercise ball lower back stretch",
        "seated lower back stretch",
        "seated hamstring stretch",
        "hamstring and calf stretch",
        "runner's stretch", "runners stretch",
        "standing hamstring and calf stretch with rope",
        "reclining big toe pose with rope",
        "seated wide angle pose sequence",
        "intermediate hip flexor and quad stretch",
        "hip flexor stretch",
        "frog stretch",
        "butterfly stretch",
        "groin stretch",
        "figure 4 stretch", "figure four stretch",
        "side lying hip adductor stretch",
        "side lying floor stretch",
        "side lying hip adduction",
        "straight leg outer hip abductor",
        "outer hip abductor",
        "hip adductor stretch",
        "ankle dorsal flexion",
    ],
    "boxing": [
        "boxing jab", "boxing right cross", "boxing right uppercut",
        "boxing left uppercut", "left hook", "right hook",
        "boxing", "boxing right cross", "boxing left cross",
    ],
    "plyometric": [
        "burpee", "box jump", "jump squat", "jump lunge",
        "scissor jumps", "star jump", "jack jump", "astride jumps",
        "jack burpee", "dumbbell burpee",
        "skips", "quick feet", "broad jump", "single leg vertical jump",
        "single leg board jump", "jump box over",
        "jump rope", "double under",
        "forward jump", "backward jump",
        "skater hops", "skate", "shuffle",
        "ski step", "ski erg", "ski ergometer",
        "mountain climber", "bear crawl",
        "inchworm", "inchworm v. 2",
        " crab twist toe touch", "crab twist",
        "medicine ball overhead slam",
        "medicine ball catch and overhead throw",
    ],
    "olympic_lifting": [
        "snatch", "power snatch", "clean", "power clean",
        "clean and jerk", "jerk", "hang clean",
        "clean pull", "snatch pull",
        "dumbbell clean", "dumbbell snatch",
        "barbell clean", "barbell snatch",
        "kettlebell clean", "kettlebell snatch",
        "kettlebell jerk", "kettlebell clean and jerk",
        "one arm clean", "one arm snatch", "one arm jerk",
        "double clean", "double jerk", "double snatch",
        "alternating hang clean", "double alternating hang clean",
        "kettlebell alternating hang clean",
        "kettlebell bottoms up clean",
        "barbell weightlifting complex",
        "weightlifting complex",
        "olympic",
    ],
    "strongman": [
        "tire flip", "car flip", "keg toss", "fingal's fingers",
        "strongman", "farmers walk", "atlas stone",
        "yoke walk", "log press",
    ],
}

# Order matters: isolation first, then mobility/helper, then compound
PATTERN_ORDER = [
    # Isolation
    "pull_bicep_isolation", "reverse_curl", "wrist_curl", "reverse_wrist_curl", "tricep_isolation",
    "push_flat_isolation", "push_vertical_isolation", "push_tricep_isolation",
    "pull_vertical_isolation", "pull_horizontal_isolation",
    "squat_isolation", "hinge_isolation", "calf_raise",
    # Mobility / helper
    "mobility_hip", "mobility_shoulder", "mobility_spine", "mobility_ankle", "mobility_wrist",
    "core_anti_extension", "core_anti_rotation", "core_flexion", "core_circumduction", "core_carries",
    "shoulder_external_rotation", "scapular_retraction",
    # Compound
    "push_up", "push_flat_compound", "push_incline_compound", "push_decline_compound",
    "push_vertical_compound", "push_tricep_compound",
    "pull_vertical_compound", "pull_horizontal_compound", "pull_shrug",
    "squat_compound", "lunge_compound", "squat_bodyweight",
    "hinge_compound", "hip_compound",
    # Special
    "cardio_plio", "boxing", "plyometric", "olympic_lifting", "strongman",
]

# Which patterns are mobility/helper
MOBILITY_HELPER = {
    "mobility_hip", "mobility_shoulder", "mobility_spine", "mobility_ankle", "mobility_wrist",
    "core_anti_extension", "core_anti_rotation", "core_carries",
    "shoulder_external_rotation", "scapular_retraction",
}

# Which patterns are compound
COMPOUND = {
    "push_flat_compound", "push_incline_compound", "push_decline_compound",
    "push_vertical_compound", "push_tricep_compound", "push_up",
    "pull_vertical_compound", "pull_horizontal_compound", "pull_shrug",
    "squat_compound", "lunge_compound", "squat_bodyweight",
    "hinge_compound", "hip_compound",
    "olympic_lifting", "strongman",
}

def classify_exercise(name):
    if not name:
        return ("unknown", 0, "isolation")
    
    name_lower = name.lower().strip()
    
    for pattern in PATTERN_ORDER:
        keywords = MOVEMENT_PATTERNS.get(pattern, [])
        for kw in keywords:
            if kw.lower() in name_lower:
                if pattern in COMPOUND:
                    return (pattern, 1, "compound")
                elif pattern in MOBILITY_HELPER:
                    return (pattern, 0, "helper")
                else:
                    return (pattern, 0, "isolation")
    
    return ("needs_review", 0, "helper")

# ---------------------------------------------------------------------------
# Run classification
# ---------------------------------------------------------------------------
conn = sqlite3.connect(DB_PATH)
conn.row_factory = sqlite3.Row

exercises = conn.execute(
    "SELECT id, name, muscle_group, equipment, movement_type, exercise_role, is_compound, primary_equipment FROM exercise_library ORDER BY id"
).fetchall()

total = len(exercises)
classified = 0
needs_review = 0

results = []

for ex in exercises:
    name = ex["name"]
    mp, ic, mt = classify_exercise(name)
    results.append({
        "id": ex["id"],
        "name": name,
        "movement_pattern": mp,
        "is_compound": ic,
        "movement_type": mt,
        "current_movement_type": ex["movement_type"],
        "current_exercise_role": ex["exercise_role"],
        "current_is_compound": ex["is_compound"],
    })
    if mp == "needs_review":
        needs_review += 1
    else:
        classified += 1

from collections import Counter
pattern_counts = Counter(r["movement_pattern"] for r in results)

print(f"Total: {total} | Classified: {classified} | Needs review: {needs_review}")
print()
print("=== Movement Pattern Distribution ===")
for pattern, count in pattern_counts.most_common():
    if pattern != "needs_review":
        print(f"  {pattern}: {count}")

print()
print(f"=== Needs Review ({needs_review} total) ===")
review_list = [r for r in results if r["movement_pattern"] == "needs_review"]
for r in review_list[:30]:
    print(f"  id={r['id']:4d} | {r['name']}")
if len(review_list) > 30:
    print(f"  ... and {len(review_list) - 30} more")

output = {
    "total": total,
    "classified": classified,
    "needs_review": needs_review,
    "results": results,
}
with open("/Users/phillipwalters/Projects/askeo/repo/backend/classification_results.json", "w") as f:
    json.dump(output, f, indent=2)

print()
print("Results written to classification_results.json")
conn.close()

