#!/usr/bin/env python3
"""Generate frontend/src/build-info.ts with the current git commit + timestamp.

Runs before `npm run build` so the built JS bundle carries the exact deploy
commit. The Settings screen reads BUILD_INFO.commit to show a version badge.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path("/Users/phillipwalters/Projects/askeo/repo")
OUT = REPO / "frontend" / "src" / "build-info.ts"


def git_sha() -> str:
    try:
        return (
            subprocess.check_output(
                ["git", "rev-parse", "HEAD"],
                cwd=REPO,
                stderr=subprocess.DEVNULL,
            )
            .decode()
            .strip()
        )
    except subprocess.CalledProcessError:
        return "unknown"


def main() -> None:
    commit = git_sha()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    short = commit[:7] if len(commit) >= 7 else commit

    content = json.dumps(
        {
            "commit": commit,
            "short": short,
            "timestamp": now,
        },
        indent=2,
    )
    module = (
        f"// Auto-generated by build-version.py — do not edit\n"
        f"// Commit {short} / {now} UTC\n\n"
        f"export const BUILD_INFO = {content};\n"
    )

    OUT.write_text(module)
    print(f"Wrote {OUT}  commit={short}  timestamp={now}")


if __name__ == "__main__":
    main()
